### ISSUE TITLE
AMEIKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK

### ISSUE THREAD

**Issue by DioBruh** [maizenalegal/cope#2]
bglh é um caos mod pra pc KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK

**Comment by maizenalegal** [comment]
kkkkkkkkk obrigado mano, se quiser me chama no discord, tem na minha página do github

**Comment by DioBruh** [comment]
vo chama sim <3, vo pega lá
